### ISSUE TITLE
Error when just one peer is in the team

### ISSUE THREAD

**Issue by cristobalmedinalopez** [P2PSP/Virtual-Room#31]
When one peer is the unique member of the team the following message is returned a lot of times: *The peer with ID Undefined has left!*

**Comment by utkarsh858** [comment]
Where does the message is returned, in the console sidebar or in the terminal. By a team do you mean a room? I made a virtual room and added myself to it but there is no message like that in the console.

**Comment by cristobalmedinalopez** [comment]
Yes, I mean room when I say team :)

Steps to replicate it:
1. go to test directory: `cd test`
2. Run test script: `./test.me`
3. Open Web welcome url in the browser: `http://localhost:3000/welcome' and press "Make a Virutal Room" to create a Room.
4. Open a New Tab and enter the URL generated to share in the previous step: something like: "http://localhost:3000/room/502d6a00".
5. Select a mp4 file in the first browser tab (step 3) and press play.
6. In this point, you can watch the video in both tabs.
7. Close the last created tab (step 4).
8. You can see a lot toast notifications with the text "The peer with ID Undefined has left!" appearing and disappering.

**Comment by jainamritanshu** [comment]
Hi @utkarsh858,
I guess this problem lies due to the try catch condition in sending chunk scope. It will iterate over all the chunks it is sending and if it can't find the appropriate peer with the peer ID it raises a toast saying this peer has left. I guess this can be easily resolved by popping out the peerID from the array on exitPeer condition. Hope it helps :smile:

**Comment by cristobalmedinalopez** [comment]
Fixed in PR #39
